"""Add source_content and generation_metadata fields

Revision ID: 3c8cf3e1b003
Revises: 22ee309eff1d
Create Date: 2025-05-24 14:06:21.320468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8cf3e1b003'
down_revision = '22ee309eff1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand_voice_versions', 'brand_voice_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('brand_voice_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('brand_voice_versions', 'status',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_constraint(None, 'brand_voice_versions', type_='foreignkey')
    op.create_foreign_key(None, 'brand_voice_versions', 'brand_voices', ['brand_voice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'brand_voice_versions', type_='foreignkey')
    op.create_foreign_key(None, 'brand_voice_versions', 'brand_voices', ['brand_voice_id'], ['id'])
    op.alter_column('brand_voice_versions', 'status',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('brand_voice_versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('brand_voice_versions', 'brand_voice_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
